### ISSUE TITLE
Geopy is at 1.11.0

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/geopy-feedstock#2]
Can we get this feedstock ticked up a version?

**Comment by ocefpaf** [comment]
Sure. See https://github.com/conda-forge/geopy-feedstock/pull/3.

BTW I started with an old version b/c `geopandas` is not compatible with the latest one yet, but now that we have `1.10.0` in the channel there is no reason to update it.

PS: Would you be wiling to be a maintainer of this feedstock :wink:? As a maintainer you could send PRs like #3  and merge them yourself.

**Comment by pmlandwehr** [comment]
Sure, I'd be fine with being a maintainer. And thanks for the bump!
